config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :posts
    end
  end
  
  resources :posts
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
reverse_geocoded_by :lat, :long,
  :address => :location
after_validation :reverse_geocode
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
       protect_from_forgery with: :null_session, only: Proc.new { |c| c.request.format.json? } 
       def create
         respond_to :json
         @newpost=Post.new
         @var1 = JSON.parse(params[:post])
         puts @var1
         puts @var1["who"]
         @newpost.img=@var1["who"]
         @newpost.lat=@var1["lat"]
         @newpost.long=@var1["long"]
         @newpost.barcode=@var1["barcode"]
         @newpost.metervalue=@var1["metervalue"]

         @newpost.save




      end
    end
  # GET /posts
      
 
  # GET /posts.json
 

  # POST /posts
  # POST /posts.json
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session, only: Proc.new { |c| c.request.format.json? }
   

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:useranme, :passwd, :lat, :long, :img, :coments, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <ul class="nav navbar-nav">

    <li class="nav-item active">
      
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">About</a>
    </li>
  </ul>
  <form class="form-inline pull-xs-right">
    <input class="form-control" type="text" placeholder="Search">
    <button class="btn btn-success-outline" type="submit">Search</button>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pixelometer</title>
  

  <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/header' %>
  <div id="modal-holder"></div>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :passwd %>
    <%= f.text_field :passwd %>
  </div>

  <div class="field">
    <%= f.label :lat %>
    <%= f.number_field :lat, :class => 'text_field', :step => 'any' %>
  </div>

  <div class="field">
    <%= f.label :long %>
    <%= f.number_field :long, :class => 'text_field', :step => 'any' %>
  </div>

  <div class="field">
    <%= f.label :img %>
    <%= f.text_field :img %>
  </div>

  <div class="field">
    <%= f.label :coments %>
    <%= f.text_field :coments %>
  </div>

  <div class="field">
    <%= f.label :metervalue %>
    <%= f.text_field :metervalue %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Posts</h1>
<%= react_component('Label', {label: 'John'}) %>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Passwd</th>
      <th>Lat</th>
      <th>Long</th>
      <th>Img</th>
      <th>Coments</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.username %></td>
        <td><%= post.passwd %></td>
        <td><%= post.lat %></td>
        <td><%= post.long %></td>
        <td><%= image_tag "data:image/jpeg;base64,#{post.img}" %></td>
        <td><%= post.coments %></td>
        <td><%= post.metervalue %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Useranme:</strong>
  <%= @post.username %>
</p>

<p>
  <strong>Passwd:</strong>
  <%= @post.passwd %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @post.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @post.long %>
</p>

<p>
  <strong>Img:</strong>
  <%= @post.img %>
</p>

<p>
  <strong>Coments:</strong>
  <%= @post.coments %>
</p>

<p>
  <strong>Value:</strong>
  <%= @post.metervalue %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>